name: Java CI with Maven

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        if: ${{ github.ref != 'refs/heads/develop' }}
        run: mvn clean test
      - name: deploy
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: echo mvn clean deploy


