name: build
on:
  workflow_call:
    inputs:
      mvn_goal:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: corretto
        cache: 'maven'
        server-id: sagebionetworks
        server-username: MAVEN_USERNAME
        server-password: MAVEN_USERPWD
    - name: Build with Maven
      run: mvn -B ${{ inputs.mvn_goal }} --file pom.xml
      env:
        MAVEN_USERNAME: ${{ secrets.PLATFORM_ARTIFACTORY_USER }}
        MAVEN_USERPWD: ${{ secrets.PLATFORM_ARTIFACTORY_PWD }}
