name: build-main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  call-build:
    if: github.event_name == 'push'
    uses: ./.github/workflows/build.yaml
    with:
      mvn_goal: deploy
    secrets: inherit
  call-test:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/build.yaml
    with:
      mvn_goal: test
    secrets: inherit

